# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 08:44
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('vehicle_num', models.TextField(max_length=128, null=True)),
                ('license_num', models.TextField(max_length=128, null=True)),
                ('national_id', models.TextField(max_length=128, null=True)),
                ('curr_lat', models.DecimalField(decimal_places=7, default=0.0, max_digits=14)),
                ('curr_lon', models.DecimalField(decimal_places=7, default=0.0, max_digits=14)),
                ('status', models.IntegerField(default=0)),
                ('driver_rating', models.DecimalField(decimal_places=2, default=2.5, max_digits=3)),
            ],
            options={
                'db_table': 'driver',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('start_lat', models.DecimalField(decimal_places=7, default=0.0, max_digits=14)),
                ('start_lon', models.DecimalField(decimal_places=7, default=0.0, max_digits=14)),
                ('end_lat', models.DecimalField(decimal_places=7, default=0.0, max_digits=14)),
                ('end_lon', models.DecimalField(decimal_places=7, default=0.0, max_digits=14)),
                ('predicted_distance', models.DecimalField(decimal_places=7, default=0.0, max_digits=14)),
                ('actual_distance', models.DecimalField(decimal_places=7, default=0.0, max_digits=14)),
                ('final_end_lat', models.DecimalField(decimal_places=7, default=0.0, max_digits=14)),
                ('final_end_lon', models.DecimalField(decimal_places=7, default=0.0, max_digits=14)),
                ('bill', models.DecimalField(decimal_places=7, default=0.0, max_digits=14)),
                ('status', models.IntegerField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joldii.DriverModel')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128, null=True)),
                ('phone', models.CharField(max_length=32, null=True, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=256, null=True)),
                ('user_type', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('user_picture', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='sessionmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joldii.UserModel'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='ord_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joldii.UserModel'),
        ),
        migrations.AddField(
            model_name='drivermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joldii.UserModel'),
        ),
    ]
