# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('national_id', models.TextField(max_length=128, null=True)),
                ('driving_license', models.TextField(max_length=128, null=True)),
                ('driving_license_image', models.TextField(max_length=128, null=True)),
                ('status', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0)),
                ('number_of_rides', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'driver',
            },
        ),
        migrations.CreateModel(
            name='DriverRatingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.TextField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_rating_model_driver', to='joldii.DriverModel')),
            ],
            options={
                'db_table': 'driver_rating',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('start_lat', models.DecimalField(decimal_places=7, default=0.0, max_digits=14)),
                ('start_lon', models.DecimalField(decimal_places=7, default=0.0, max_digits=14)),
                ('end_lat', models.DecimalField(decimal_places=7, default=0.0, max_digits=14)),
                ('end_lon', models.DecimalField(decimal_places=7, default=0.0, max_digits=14)),
                ('predicted_distance', models.DecimalField(decimal_places=7, default=0.0, max_digits=14)),
                ('actual_distance', models.DecimalField(decimal_places=7, default=0.0, max_digits=14)),
                ('final_end_lat', models.DecimalField(decimal_places=7, default=0.0, max_digits=14)),
                ('final_end_lon', models.DecimalField(decimal_places=7, default=0.0, max_digits=14)),
                ('bill', models.DecimalField(decimal_places=7, default=0.0, max_digits=14)),
                ('status', models.IntegerField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joldii.DriverModel')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='RideModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('pickup_lat', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('pickup_lon', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('drop_lat', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('drop_lon', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('path', models.CharField(blank=True, max_length=1024, null=True)),
                ('distance', models.FloatField(default=0)),
                ('duration', models.BigIntegerField(default=0)),
                ('base_fare', models.FloatField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('total_bill', models.FloatField(default=0)),
                ('order_status', models.IntegerField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_model_driver', to='joldii.DriverModel')),
            ],
            options={
                'db_table': 'ride',
            },
        ),
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('current_lat', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('current_lon', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('is_driver', models.BooleanField(default=False)),
                ('driver_status', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('current_ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_model_current_ride', to='joldii.RideModel')),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128, null=True)),
                ('phone', models.CharField(max_length=32, null=True, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=256, null=True)),
                ('user_type', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('user_picture', models.CharField(max_length=128, null=True)),
                ('average_rating', models.FloatField(default=0)),
                ('number_of_rides', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserRatingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.TextField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rating_model_driver', to='joldii.DriverModel')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rating_model_ride', to='joldii.RideModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rating_model_user', to='joldii.UserModel')),
            ],
            options={
                'db_table': 'user_rating',
            },
        ),
        migrations.CreateModel(
            name='VehicleClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=128)),
                ('maximum_passenger', models.IntegerField(default=1)),
                ('base_fare', models.FloatField(default=0)),
                ('per_kilometer_fare', models.FloatField(default=0)),
                ('per_minute_fare', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'vehicle_class',
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('registration_number', models.TextField(max_length=128, unique=True)),
                ('engine_number', models.TextField(max_length=128, null=True)),
                ('chassis_number', models.TextField(max_length=128, null=True)),
                ('registration_certificate_image', models.TextField(max_length=128, null=True)),
                ('tax_token_image', models.TextField(max_length=128, null=True)),
                ('insurance_image', models.TextField(max_length=128, null=True)),
                ('color', models.TextField(max_length=128, null=True)),
                ('status', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0)),
                ('number_of_rides', models.IntegerField(default=0)),
                ('driver', models.ManyToManyField(related_name='vehicle_model_driver', to='joldii.DriverModel')),
                ('ride_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_model_ride_class', to='joldii.VehicleClassModel')),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.AddField(
            model_name='sessionmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_user_user', to='joldii.UserModel'),
        ),
        migrations.AddField(
            model_name='ridemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_model_user', to='joldii.UserModel'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='ord_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joldii.UserModel'),
        ),
        migrations.AddField(
            model_name='driverratingmodel',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_rating_model_ride', to='joldii.RideModel'),
        ),
        migrations.AddField(
            model_name='driverratingmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_rating_model_user', to='joldii.UserModel'),
        ),
        migrations.AddField(
            model_name='drivermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_model_user', to='joldii.UserModel'),
        ),
    ]
