from dashboard.views.web import dashboard
from dashboard.views.web import login
from dashboard.views.web import users
from dashboard.views.web import rides
from dashboard.views.web import ride_detail
from dashboard.views.web import ride_settings
from dashboard.views.web import promo
from dashboard.views.web import accounts
from dashboard.views.web import user_directory
from dashboard.views.web import vehicle_list